### ISSUE TITLE
Content is redrawn when first loaded

### ISSUE THREAD

**Issue by notmessenger** [SpikedKira/jQuery.fn.twbsResponsivePagination#1]
When viewing the demo app all of the page options are displayed, wrapping to a second line and then after a brief moment the plugin kicks in and redraws on the screen, making use of the "..." entries.  Is it possible to prevent this from occurring, and only presenting the user with the final desired visual outcome? (I have not dug through the code).

**Comment by SpikedKira** [comment]
If this is a requirement, I suggest:
$('.pagination').hide().twbsResponsivePagination().show();

However, please see "additional notes" here: http://api.jquery.com/width/

This plugin is design to react to the way that things are being displayed, therefor it is against the core of the plugin to hide the elements being worked on while attempting to react to their display.
